# Generated by Django 3.0.3 on 2020-08-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Everything', '0002_customer_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
