# Generated by Django 3.0.3 on 2020-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Everything', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='takeway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
