# Generated by Django 3.0.3 on 2020-08-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Everything', '0005_auto_20200820_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='takeway',
            new_name='takeaway',
        ),
    ]
