# Generated by Django 3.0.3 on 2020-08-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Everything', '0006_auto_20200820_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
